//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrollment
    {
        public int EnrollmentID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public string Grade { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
